import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import BackgroundEffect from "@/components/BackgroundEffect";

const inter = Inter({ subsets: ["latin"],
  subsets: ["latin"],
  variable: "--font-inter",
   
 });

export const metadata = {
  title: "Rency C. Delos Santos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable, "bg-background text-foreground")}>
        {children}
        <BackgroundEffect />
      </body>
    </html>
  );
}
