/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: prakashchatterjee35 (https://sketchfab.com/prakashchatterjee35)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/builder-hut-5d5262d5432e4ddf947ed82e28228d4e
Title: Builder Hut
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Hut(props) {
  const { nodes, materials } = useGLTF('/models/builder_hut.glb');

  return (
    <group {...props} dispose={null}>
    scale={[3,3,3]}
    position={[0, -2, 0]}
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.builder_hut_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.builder_hut_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.builder_hut_3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.builder_hut_4}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/builder_hut.glb')